"""empty message

Revision ID: cb0067f6680d
Revises: 0c748785afb2
Create Date: 2022-05-27 12:46:28.480802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0067f6680d'
down_revision = '0c748785afb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('varieties', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('varieties', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('wines', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('wines', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wines', 'updated_at')
    op.drop_column('wines', 'created_at')
    op.drop_column('varieties', 'updated_at')
    op.drop_column('varieties', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
